// Card images
export const CardImages = {
  s6: require('./images/cards/s-6.png'),
  s7: require('./images/cards/s-7.png'),
  s8: require('./images/cards/s-8.png'),
  s9: require('./images/cards/s-9.png'),
  s10: require('./images/cards/s-10.png'),
  sj: require('./images/cards/s-j.png'),
  sq: require('./images/cards/s-q.png'),
  sk: require('./images/cards/s-k.png'),
  sa: require('./images/cards/s-a.png'),
  c6: require('./images/cards/c-6.png'),
  c7: require('./images/cards/c-7.png'),
  c8: require('./images/cards/c-8.png'),
  c9: require('./images/cards/c-9.png'),
  c10: require('./images/cards/c-10.png'),
  cj: require('./images/cards/c-j.png'),
  cq: require('./images/cards/c-q.png'),
  ck: require('./images/cards/c-k.png'),
  ca: require('./images/cards/c-a.png'),
  h6: require('./images/cards/h-6.png'),
  h7: require('./images/cards/h-7.png'),
  h8: require('./images/cards/h-8.png'),
  h9: require('./images/cards/h-9.png'),
  h10: require('./images/cards/h-10.png'),
  hj: require('./images/cards/h-j.png'),
  hq: require('./images/cards/h-q.png'),
  hk: require('./images/cards/h-k.png'),
  ha: require('./images/cards/h-a.png'),
  d6: require('./images/cards/d-6.png'),
  d7: require('./images/cards/d-7.png'),
  d8: require('./images/cards/d-8.png'),
  d9: require('./images/cards/d-9.png'),
  d10: require('./images/cards/d-10.png'),
  dj: require('./images/cards/d-j.png'),
  dq: require('./images/cards/d-q.png'),
  dk: require('./images/cards/d-k.png'),
  da: require('./images/cards/d-a.png')
}

// List of card ranks
export const CardRanks = ['6', '7', '8', '9', '10', 'j', 'q', 'k', 'a'];
